#pragma once

#ifndef BURNERNET_OBFUSCATE_STRINGS
#if defined(BURNER_OBFUSCATE_STRINGS)
#define BURNERNET_OBFUSCATE_STRINGS BURNER_OBFUSCATE_STRINGS
#else
#define BURNERNET_OBFUSCATE_STRINGS 1
#endif
#endif

#ifndef BURNERNET_HARDEN_IMPORTS
#define BURNERNET_HARDEN_IMPORTS 0
#endif

#ifndef BURNERNET_DIAGNOSTIC_STRINGS
#define BURNERNET_DIAGNOSTIC_STRINGS 1
#endif

#ifndef BURNERNET_MAXIMUM_GHOST
#define BURNERNET_MAXIMUM_GHOST 0
#endif

#if BURNERNET_OBFUSCATE_STRINGS != 0 && BURNERNET_OBFUSCATE_STRINGS != 1
#error "BURNERNET_OBFUSCATE_STRINGS must be defined as 0 or 1"
#endif

#if BURNERNET_HARDEN_IMPORTS != 0 && BURNERNET_HARDEN_IMPORTS != 1
#error "BURNERNET_HARDEN_IMPORTS must be defined as 0 or 1"
#endif

#if BURNERNET_DIAGNOSTIC_STRINGS != 0 && BURNERNET_DIAGNOSTIC_STRINGS != 1
#error "BURNERNET_DIAGNOSTIC_STRINGS must be defined as 0 or 1"
#endif

#if BURNERNET_MAXIMUM_GHOST != 0 && BURNERNET_MAXIMUM_GHOST != 1
#error "BURNERNET_MAXIMUM_GHOST must be defined as 0 or 1"
#endif

#if BURNERNET_MAXIMUM_GHOST && !defined(_WIN32)
#error "BURNERNET_MAXIMUM_GHOST is supported only on Windows in BurnerNet v1.4"
#endif
