#!/usr/bin/env python3

import argparse
import os
import sys
from pathlib import Path

ERROR_CODE_NAMES = [
    "None",
    "DisabledBackend",
    "InitCurl",
    "NoCurlHandle",
    "CurlGeneric",
    "VerifyGeneric",
    "SigProvider",
    "SigEmpty",
    "SigHeaderMissing",
    "SigCompute",
    "SigMismatch",
    "BootstrapConfig",
    "BootstrapAddDir",
    "BootstrapLoad",
    "BootstrapSkip",
    "BootstrapLoaded",
    "BootstrapWinOnly",
    "BootstrapIntegrityCfg",
    "BootstrapIntegrityMissing",
    "BootstrapIntegrityCompute",
    "BootstrapIntegrityMismatch",
    "BootstrapModulePath",
    "BodyTooLarge",
    "InvalidHeader",
    "RedirectAuth",
    "BootstrapDllDirs",
    "RequestBodyTooLarge",
    "CurlApiIncomplete",
    "CurlApiUntrusted",
    "PreFlightAbort",
    "HeartbeatAbort",
    "TlsVerificationFailed",
]


CONFIG_TEMPLATE = """#pragma once
#include <cstdint>
#include <string>
#include <vector>

// Generated by tools/generate_config.py config:generate
// Project-specific security constants for BurnerNet.
// Point BurnerNet at this file with BURNERNET_USER_CONFIG_HEADER="BurnerNet_Config.h".

#define BURNERNET_HAS_CUSTOM_ERROR_CODE_ENUM 1

namespace burner::net {{

enum class ErrorCode : uint32_t {{
{error_code_enum}
}};

}} // namespace burner::net

namespace burnernet_config {{

// 1. Error Code Polymorphism
// Masks the integer output of ErrorCodeToString.
#define BURNERNET_ERROR_XOR 0x{error_xor}u

// 2. Security Lifecycle Hooks (Weapon Mounts)
// Override these to plug in your own Anti-RE or Logging.

// Called after signature verification. Use this to report tampered responses.
#ifndef BURNERNET_ON_SIGNATURE_VERIFIED
    #define BURNERNET_ON_SIGNATURE_VERIFIED(success, reason) \\
        do {{                                                 \\
            (void)(success);                                  \\
            (void)(reason);                                   \\
        }} while (0)
#endif

// Called when the library detects memory patching in sensitive logic.
#ifndef BURNERNET_ON_TAMPER
    #include <cstdlib>
    #define BURNERNET_ON_TAMPER() std::abort()
#endif

// Called when a transport error occurs. Use this for silent telemetry.
#ifndef BURNERNET_ON_ERROR
    #define BURNERNET_ON_ERROR(code, url) \\
        do {{                              \\
            (void)(code);                  \\
            (void)(url);                   \\
        }} while (0)
#endif

// Project-specific seed reserved for your own hook logic.
#define BURNERNET_SECURITY_SEED 0x{security_seed}u

// 3. String Obfuscation (Weapon Mount)
// Replace this with your own XOR/Crypter (e.g. xorstr or a custom loop).
#ifndef BURNER_OBF_LITERAL
    #define BURNER_OBF_LITERAL(str) std::string(str)
#endif

// 4. Stealth User-Agent Override
// Return an empty string to keep ClientConfig::user_agent.
#ifndef BURNERNET_GET_USER_AGENT
    #define BURNERNET_GET_USER_AGENT() std::string("")
#endif

// 5. Dependency Hiding
// Rename your DLLs on disk and update this list to hide your networking stack.
inline const std::vector<std::wstring> GetTrustedDependencies() {{
    return {{
        L"zlib1.dll",
        L"libcurl.dll"
    }};
}}

}} // namespace burnernet_config
"""


def random_u32_hex():
    return os.urandom(4).hex().upper()


def generate_error_code_enum() -> str:
    used = set()
    lines = []
    for name in ERROR_CODE_NAMES:
        while True:
            value = int.from_bytes(os.urandom(4), byteorder="big")
            if value not in used:
                used.add(value)
                lines.append(f"    {name} = 0x{value:08X}u,")
                break
    return "\n".join(lines)


def generate_config(output_path: Path):
    content = CONFIG_TEMPLATE.format(
        error_xor=random_u32_hex(),
        error_code_enum=generate_error_code_enum(),
        security_seed=random_u32_hex(),
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    sys.stdout.write(f"Wrote {output_path}\n")


def default_output_path() -> Path:
    return Path.cwd() / "BurnerNet_Config.h"


def build_parser():
    parser = argparse.ArgumentParser(description="Generate a BurnerNet project config header.")
    parser.add_argument(
        "--output",
        "--out",
        dest="output",
        type=Path,
        help="Output header path. Defaults to <repo>/BurnerNet_Config.h.",
    )
    subparsers = parser.add_subparsers(dest="command")

    generate = subparsers.add_parser("config:generate", help="Generate a project-specific BurnerNet config header")
    generate.add_argument(
        "--output",
        "--out",
        dest="output",
        type=Path,
        default="BurnerNet_Config.h",
        help="Output header path (default: BurnerNet_Config.h)",
    )

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if args.command is None or args.command == "config:generate":
        output_path = Path(args.output) if args.output is not None else default_output_path()
        generate_config(output_path)
        return 0

    parser.error(f"unknown command: {args.command}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
